apiVersion: v1
kind: Secret
metadata:
  name: falcosidekick-ui
  namespace: default
  labels:
    app.kubernetes.io/name: falcosidekick-ui
    helm.sh/chart: falcosidekick-0.7.2
    app.kubernetes.io/instance: falcosidekick
    app.kubernetes.io/managed-by: Helm
type: Opaque
data:
  FALCOSIDEKICK_UI_USER: "YWRtaW46YWRtaW4="
---
apiVersion: v1
kind: Secret
metadata:
  name: falcosidekick-ui-redis
  namespace: default
  labels:
    app.kubernetes.io/name: falcosidekick-ui
    helm.sh/chart: falcosidekick-0.7.2
    app.kubernetes.io/instance: falcosidekick
    app.kubernetes.io/managed-by: Helm
type: Opaque
data:
---
