apiVersion: v1
kind: Secret
metadata:
  name: falcosidekick
  namespace: default
  labels:
    app.kubernetes.io/name: falcosidekick
    helm.sh/chart: falcosidekick-0.6.0
    app.kubernetes.io/instance: falcosidekick
    app.kubernetes.io/managed-by: Helm
type: Opaque
data:
  # Slack Output
  SLACK_WEBHOOKURL: ""
  SLACK_CHANNEL: ""
  SLACK_OUTPUTFORMAT: "YWxs"
  SLACK_FOOTER: ""
  SLACK_ICON: ""
  SLACK_USERNAME: ""
  SLACK_MINIMUMPRIORITY: ""
  SLACK_MESSAGEFORMAT: ""

  # RocketChat Output
  ROCKETCHAT_WEBHOOKURL: ""
  ROCKETCHAT_OUTPUTFORMAT: "YWxs"
  ROCKETCHAT_ICON: ""
  ROCKETCHAT_USERNAME: ""
  ROCKETCHAT_MINIMUMPRIORITY: ""
  ROCKETCHAT_MESSAGEFORMAT: ""
  ROCKETCHAT_MUTUALTLS: "ZmFsc2U="
  ROCKETCHAT_CHECKCERT: "dHJ1ZQ=="

  # Mattermost Output
  MATTERMOST_WEBHOOKURL: ""
  MATTERMOST_OUTPUTFORMAT: "YWxs"
  MATTERMOST_FOOTER: ""
  MATTERMOST_ICON: ""
  MATTERMOST_USERNAME: ""
  MATTERMOST_MINIMUMPRIORITY: ""
  MATTERMOST_MESSAGEFORMAT: ""
  MATTERMOST_MUTUALTLS: "ZmFsc2U="
  MATTERMOST_CHECKCERT: "dHJ1ZQ=="

  # Teams Output
  TEAMS_WEBHOOKURL: ""
  TEAMS_OUTPUTFORMAT: "YWxs"
  TEAMS_ACTIVITYIMAGE: ""
  TEAMS_MINIMUMPRIORITY: ""

  # Datadog Output
  DATADOG_APIKEY: ""
  DATADOG_HOST: ""
  DATADOG_MINIMUMPRIORITY: ""

  # AlertManager Output
  ALERTMANAGER_HOSTPORT: ""
  ALERTMANAGER_ENDPOINT: "L2FwaS92MS9hbGVydHM="
  ALERTMANAGER_EXPIRESAFTER: ""
  ALERTMANAGER_MINIMUMPRIORITY: ""
  ALERTMANAGER_MUTUALTLS: "ZmFsc2U="
  ALERTMANAGER_CHECKCERT: "dHJ1ZQ=="

  # InfluxDB Output
  INFLUXDB_USER: ""
  INFLUXDB_PASSWORD: ""
  INFLUXDB_TOKEN: ""
  INFLUXDB_HOSTPORT: ""
  INFLUXDB_ORGANIZATION: ""
  INFLUXDB_PRECISION: "bnM="
  INFLUXDB_MINIMUMPRIORITY: ""
  INFLUXDB_DATABASE: "ZmFsY28="
  INFLUXDB_MUTUALTLS: "ZmFsc2U="
  INFLUXDB_CHECKCERT: "dHJ1ZQ=="

  # AWS Output
  AWS_ACCESSKEYID: ""
  AWS_SECRETACCESSKEY: ""
  AWS_REGION: ""
  AWS_CHECKIDENTITY: "dHJ1ZQ=="
  AWS_LAMBDA_FUNCTIONNAME: ""
  AWS_LAMBDA_MINIMUMPRIORITY: ""
  AWS_CLOUDWATCHLOGS_LOGGROUP: ""
  AWS_CLOUDWATCHLOGS_LOGSTREAM: ""
  AWS_CLOUDWATCHLOGS_MINIMUMPRIORITY: ""
  AWS_SNS_TOPICARN: ""
  AWS_SNS_RAWJSON: "ZmFsc2U="
  AWS_SNS_MINIMUMPRIORITY: ""
  AWS_SQS_URL: ""
  AWS_SQS_MINIMUMPRIORITY: ""
  AWS_S3_BUCKET: ""
  AWS_S3_PREFIX: ""
  AWS_S3_MINIMUMPRIORITY: ""
  AWS_KINESIS_STREAMNAME: ""
  AWS_KINESIS_MINIMUMPRIORITY: ""
  AWS_SECURITYLAKE_BUCKET: ""
  AWS_SECURITYLAKE_REGION: ""
  AWS_SECURITYLAKE_PREFIX: ""
  AWS_SECURITYLAKE_ACCOUNTID: ""
  AWS_SECURITYLAKE_INTERVAL: "NQ=="
  AWS_SECURITYLAKE_BATCHSIZE: "MTAwMA=="
  AWS_SECURITYLAKE_MINIMUMPRIORITY: ""

  # SMTP Output
  SMTP_USER: ""
  SMTP_PASSWORD: ""
  SMTP_AUTHMECHANISM: "cGxhaW4="
  SMTP_HOSTPORT: ""
  SMTP_FROM: ""
  SMTP_TO: ""
  SMTP_TOKEN: ""
  SMTP_IDENTITY: ""
  SMTP_TRACE: ""
  SMTP_OUTPUTFORMAT: "aHRtbA=="
  SMTP_MINIMUMPRIORITY: ""

  # OpsGenie Output
  OPSGENIE_APIKEY: ""
  OPSGENIE_REGION: ""
  OPSGENIE_MINIMUMPRIORITY: ""
  OPSGENIE_MUTUALTLS: "ZmFsc2U="
  OPSGENIE_CHECKCERT: "dHJ1ZQ=="

  # Discord Output
  DISCORD_WEBHOOKURL: ""
  DISCORD_ICON: ""
  DISCORD_MINIMUMPRIORITY: ""

  # GCP Output
  GCP_CREDENTIALS: ""
  GCP_PUBSUB_PROJECTID: ""
  GCP_PUBSUB_TOPIC: ""
  GCP_PUBSUB_MINIMUMPRIORITY: ""
  GCP_STORAGE_BUCKET: ""
  GCP_STORAGE_PREFIX: ""
  GCP_STORAGE_MINIMUMPRIORITY: "ZGVidWc="
  GCP_CLOUDFUNCTIONS_NAME: ""
  GCP_CLOUDFUNCTIONS_MINIMUMPRIORITY: ""
  GCP_CLOUDRUN_ENDPOINT: ""
  GCP_CLOUDRUN_JWT: ""
  GCP_CLOUDRUN_MINIMUMPRIORITY: ""

  # GoogleChat Output
  GOOGLECHAT_WEBHOOKURL: ""
  GOOGLECHAT_OUTPUTFORMAT: "YWxs"
  GOOGLECHAT_MINIMUMPRIORITY: ""
  GOOGLECHAT_MESSAGEFORMAT: ""

  # ElasticSearch Output
  ELASTICSEARCH_HOSTPORT: ""
  ELASTICSEARCH_INDEX: "ZmFsY28="
  ELASTICSEARCH_TYPE: "X2RvYw=="
  ELASTICSEARCH_SUFFIX: "ZGFpbHk="
  ELASTICSEARCH_MINIMUMPRIORITY: ""
  ELASTICSEARCH_MUTUALTLS: "ZmFsc2U="
  ELASTICSEARCH_CHECKCERT: "dHJ1ZQ=="
  ELASTICSEARCH_USERNAME: ""
  ELASTICSEARCH_PASSWORD: ""

  # Loki Output
  LOKI_HOSTPORT: ""
  LOKI_ENDPOINT: "L2xva2kvYXBpL3YxL3B1c2g="
  LOKI_USER: ""
  LOKI_APIKEY: ""
  LOKI_TENANT: ""
  LOKI_EXTRALABELS: ""
  LOKI_MINIMUMPRIORITY: ""
  LOKI_MUTUALTLS: "ZmFsc2U="
  LOKI_CHECKCERT: "dHJ1ZQ=="

  # Prometheus Output
  PROMETHEUS_EXTRALABELS: ""

  # Nats Output
  NATS_HOSTPORT: ""
  NATS_MINIMUMPRIORITY: ""
  NATS_MUTUALTLS: "ZmFsc2U="
  NATS_CHECKCERT: "dHJ1ZQ=="

  # Stan Output
  STAN_HOSTPORT: ""
  STAN_CLUSTERID: ""
  STAN_CLIENTID: ""
  STAN_MINIMUMPRIORITY: ""
  STAN_MUTUALTLS: "ZmFsc2U="
  STAN_CHECKCERT: "dHJ1ZQ=="

  # Statsd
  STATSD_FORWARDER: ""
  STATSD_NAMESPACE: "ZmFsY29zaWRla2ljay4="

  # Dogstatsd
  DOGSTATSD_FORWARDER: ""
  DOGSTATSD_NAMESPACE: "ZmFsY29zaWRla2ljay4="
  DOGSTATSD_TAGS: ""

  # WebHook Output
  WEBHOOK_ADDRESS: ""
  WEBHOOK_CUSTOMHEADERS: ""
  WEBHOOK_MINIMUMPRIORITY: ""
  WEBHOOK_MUTUALTLS: "ZmFsc2U="
  WEBHOOK_CHECKCERT: "dHJ1ZQ=="

  # Azure Output
  AZURE_EVENTHUB_NAME: ""
  AZURE_EVENTHUB_NAMESPACE: ""
  AZURE_EVENTHUB_MINIMUMPRIORITY: ""

  # Kafka Output
  KAFKA_HOSTPORT: ""
  KAFKA_TOPIC: ""
  KAFKA_SASL: ""
  KAFKA_USERNAME: ""
  KAFKA_PASSWORD: ""
  KAFKA_ASYNC: "ZmFsc2U="
  KAFKA_REQUIREDACKS: "Tk9ORQ=="
  KAFKA_COMPRESSION: "Tk9ORQ=="
  KAFKA_BALANCER: "cm91bmRfcm9iaW4="
  KAFKA_CLIENTID: ""
  KAFKA_MINIMUMPRIORITY: ""

  # PagerDuty Output
  PAGERDUTY_ROUTINGKEY: ""
  PAGERDUTY_MINIMUMPRIORITY: ""

  # Kubeless Output
  KUBELESS_FUNCTION: ""
  KUBELESS_NAMESPACE: ""
  KUBELESS_PORT: "ODA4MA=="
  KUBELESS_MINIMUMPRIORITY: ""
  KUBELESS_MUTUALTLS: "ZmFsc2U="
  KUBELESS_CHECKCERT: "dHJ1ZQ=="

  # OpenFaaS
  OPENFAAS_GATEWAYNAMESPACE: "b3BlbmZhYXM="
  OPENFAAS_GATEWAYSERVICE: "Z2F0ZXdheQ=="
  OPENFAAS_FUNCTIONNAME: ""
  OPENFAAS_FUNCTIONNAMESPACE: "b3BlbmZhYXMtZm4="
  OPENFAAS_GATEWAYPORT: "ODA4MA=="
  OPENFAAS_MINIMUMPRIORITY: ""
  OPENFAAS_MUTUALTLS: "ZmFsc2U="
  OPENFAAS_CHECKCERT: "dHJ1ZQ=="

  # Cloud Events Output
  CLOUDEVENTS_ADDRESS: ""
  CLOUDEVENTS_EXTENSION: ""
  CLOUDEVENTS_MINIMUMPRIORITY: ""

  # RabbitMQ Output
  RABBITMQ_URL: ""
  RABBITMQ_QUEUE: ""
  RABBITMQ_MINIMUMPRIORITY: "ZGVidWc="

  # Wavefront Output
  WAVEFRONT_ENDPOINTTYPE: ""
  WAVEFRONT_ENDPOINTHOST: ""
  WAVEFRONT_ENDPOINTTOKEN: ""
  WAVEFRONT_ENDPOINTMETRICPORT: "Mjg3OA=="
  WAVEFRONT_FLUSHINTERVALSECONDS: "MQ=="
  WAVEFRONT_BATCHSIZE: "MTAwMDA="
  WAVEFRONT_METRICNAME: "ZmFsY28uYWxlcnQ="
  WAVEFRONT_MINIMUMPRIORITY: "ZGVidWc="

  # Grafana Output
  GRAFANA_HOSTPORT: ""
  GRAFANA_APIKEY: ""
  GRAFANA_DASHBOARDID: ""
  GRAFANA_PANELID: ""
  GRAFANA_ALLFIELDSASTAGS: "ZmFsc2U="
  GRAFANA_MUTUALTLS: "ZmFsc2U="
  GRAFANA_CHECKCERT: "dHJ1ZQ=="
  GRAFANA_MINIMUMPRIORITY: ""

  # Fission Output
  FISSION_FUNCTION: ""
  FISSION_ROUTERNAMESPACE: "Zmlzc2lvbg=="
  FISSION_ROUTERSERVICE: "cm91dGVy"
  FISSION_ROUTERPORT: "ODA="
  FISSION_MINIMUMPRIORITY: ""
  FISSION_MUTUALTLS: "ZmFsc2U="
  FISSION_CHECKCERT: "dHJ1ZQ=="

  # Yandex Output
  YANDEX_ACCESSKEYID:  ""
  YANDEX_SECRETACCESSKEY: ""
  YANDEX_REGION: ""
  YANDEX_S3_ENDPOINT: ""
  YANDEX_S3_BUCKET: ""
  YANDEX_S3_PREFIX: ""
  YANDEX_S3_MINIMUMPRIORITY: ""
  YANDEX_DATASTREAMS_ENDPOINT: ""
  YANDEX_DATASTREAMS_STREAMNAME: ""
  YANDEX_DATASTREAMS_MINIMUMPRIORITY: ""

  # KafkaRest Output
  KAFKAREST_ADDRESS: ""
  KAFKAREST_VERSION: "Mg=="
  KAFKAREST_MINIMUMPRIORITY : ""
  KAFKAREST_MUTUALTLS : "ZmFsc2U="
  KAFKAREST_CHECKCERT : "dHJ1ZQ=="

  # Syslog
  SYSLOG_HOST: ""
  SYSLOG_PORT: ""
  SYSLOG_PROTOCOL: "dGNw"
  SYSLOG_FORMAT: "anNvbg=="
  SYSLOG_MINIMUMPRIORITY : ""

  # Zoho Cliq
  CLIQ_WEBHOOKURL: ""
  CLIQ_ICON: ""
  CLIQ_USEEMOJI: "dHJ1ZQ=="
  CLIQ_OUTPUTFORMAT: "YWxs"
  CLIQ_MESSAGEFORMAT: ""
  CLIQ_MINIMUMPRIORITY : ""

  # Policy Reporter
  POLICYREPORT_ENABLED: "ZmFsc2U="
  POLICYREPORT_KUBECONFIG: "fi8ua3ViZS9jb25maWc="
  POLICYREPORT_MAXEVENTS: "MTAwMA=="
  POLICYREPORT_PRUNEBYPRIORITY: "ZmFsc2U="
  POLICYREPORT_MINIMUMPRIORITY : ""

  # Node Red
  NODERED_ADDRESS: ""
  NODERED_USER: ""
  NODERED_PASSWORD: ""
  NODERED_CUSTOMHEADERS: ""
  NODERED_CHECKCERT : "dHJ1ZQ=="
  NODERED_MINIMUMPRIORITY : ""

  # MQTT
  MQTT_BROKER: ""
  MQTT_TOPIC: "ZmFsY28vZXZlbnRz"
  MQTT_QOS: "MA=="
  MQTT_RETAINED : "ZmFsc2U="
  MQTT_USER: ""
  MQTT_PASSWORD: ""
  MQTT_CHECKCERT : "dHJ1ZQ=="
  MQTT_MINIMUMPRIORITY : ""

  # Zincsearch
  ZINCSEARCH_HOSTPORT: ""
  ZINCSEARCH_INDEX: "ZmFsY28="
  ZINCSEARCH_USERNAME: ""
  ZINCSEARCH_PASSWORD: ""
  ZINCSEARCH_CHECKCERT : "dHJ1ZQ=="
  ZINCSEARCH_MINIMUMPRIORITY : ""

  # Gotify
  GOTIFY_HOSTPORT: ""
  GOTIFY_TOKEN: ""
  GOTIFY_FORMAT: "bWFya2Rvd24="
  GOTIFY_CHECKCERT : "dHJ1ZQ=="
  GOTIFY_MINIMUMPRIORITY : ""

  # Tekton
  TEKTON_EVENTLISTENER: ""
  TEKTON_CHECKCERT : "dHJ1ZQ=="
  TEKTON_MINIMUMPRIORITY : ""

  # Spyderbat
  SPYDERBAT_ORGUID: ""
  SPYDERBAT_APIKEY: ""
  SPYDERBAT_APIURL: "aHR0cHM6Ly9hcGkuc3B5ZGVyYmF0LmNvbQ=="
  SPYDERBAT_SOURCE: "ZmFsY29zaWRla2ljaw=="
  SPYDERBAT_SOURCEDESCRIPTION: ""
  SPYDERBAT_MINIMUMPRIORITY : ""

  # TimescaleDB
  TIMESCALEDB_HOST: ""
  TIMESCALEDB_PORT: "NTQzMg=="
  TIMESCALEDB_USER: "cG9zdGdyZXM="
  TIMESCALEDB_PASSWORD: "cG9zdGdyZXM="
  TIMESCALEDB_DATABASE: ""
  TIMESCALEDB_HYPERTABLENAME: "ZmFsY29fZXZlbnRz"
  TIMESCALEDB_MINIMUMPRIORITY : ""

  # WebUI Output
---
