apiVersion: v1
kind: ServiceAccount
metadata:
  name: falco
  namespace: default
  labels:
    helm.sh/chart: falco-5.0.3
    app.kubernetes.io/name: falco
    app.kubernetes.io/instance: falco
    app.kubernetes.io/version: "0.41.1"
    app.kubernetes.io/managed-by: Helm
---
