apiVersion: v1
kind: ServiceAccount
metadata:
  name: falco
  namespace: default
  labels:
    helm.sh/chart: falco-4.5.1
    app.kubernetes.io/name: falco
    app.kubernetes.io/instance: falco
    app.kubernetes.io/version: "0.38.1"
    app.kubernetes.io/managed-by: Helm
---
